// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Compare from '../src/commands/compare.js'
import Eta from '../src/commands/eta.js'
import Growth from '../src/commands/growth.js'
import PrestigeCycle from '../src/commands/prestigeCycle.js'
import Report from '../src/commands/report.js'
import Simulate from '../src/commands/simulate.js'
import Tune from '../src/commands/tune.js'
import Validate from '../src/commands/validate.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['compare', 'eta', 'growth', 'prestige-cycle', 'report', 'simulate', 'tune', 'validate'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'compare': Compare,
  'eta': Eta,
  'growth': Growth,
  'prestige-cycle': PrestigeCycle,
  'report': Report,
  'simulate': Simulate,
  'tune': Tune,
  'validate': Validate
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'compare': {
      name: 'compare',
      description: 'Compare two scenarios via measured simulation metrics',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1176,"end":1181,"loc":{"start":{"line":37,"column":54,"index":1176},"end":{"line":37,"column":59,"index":1181}},"value":false}}]}, validator: '(val) => true' },
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1578,"end":1583,"loc":{"start":{"line":43,"column":44,"index":1578},"end":{"line":43,"column":49,"index":1583}},"value":false}}]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Required for etaToTargetWorth metric, optional otherwise', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max duration for etaToTargetWorth metric simulation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1828,"end":1833,"loc":{"start":{"line":47,"column":53,"index":1828},"end":{"line":47,"column":58,"index":1833}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'metric': { type: 'z.enum.default', required: true, hasDefault: true, default: "endNetWorth", description: 'Comparison metric', enumValues: ["endMoney","endNetWorth","etaToTargetWorth","droppedRate"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"endNetWorth"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/compare'
    },
  'eta': {
      name: 'eta',
      description: 'Estimate time to target money or net worth',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":643,"end":648,"loc":{"start":{"line":19,"column":54,"index":643},"end":{"line":19,"column":59,"index":648}},"value":false}}]}, validator: '(val) => true' },
        'target-money': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target money NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target net worth NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'mode': { type: 'z.enum.default', required: true, hasDefault: true, default: "simulate", description: 'ETA mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"simulate"}]}, validator: '(val) => true' },
        'diff': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Compare with another mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max simulate duration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1178,"end":1183,"loc":{"start":{"line":28,"column":53,"index":1178},"end":{"line":28,"column":58,"index":1183}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'include-run': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include detailed run payload in simulate mode output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1282,"end":1287,"loc":{"start":{"line":29,"column":53,"index":1282},"end":{"line":29,"column":58,"index":1287}},"value":false}}]}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Fast simulation mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1419,"end":1424,"loc":{"start":{"line":32,"column":44,"index":1419},"end":{"line":32,"column":49,"index":1424}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/eta'
    },
  'growth': {
      name: 'growth',
      description: 'Analyze growth regime from simulation trace',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":649,"end":654,"loc":{"start":{"line":19,"column":54,"index":649},"end":{"line":19,"column":59,"index":654}},"value":false}}]}, validator: '(val) => true' },
        'window': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Window sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":769,"end":771,"loc":{"start":{"line":22,"column":45,"index":769},"end":{"line":22,"column":47,"index":771}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'series': { type: 'z.enum.default', required: true, hasDefault: true, default: "money", description: 'Series type', enumValues: ["money","netWorth"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"money"}]}, validator: '(val) => true' },
        'trace-every': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 1, description: 'Trace every N steps', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":958,"end":959,"loc":{"start":{"line":24,"column":52,"index":958},"end":{"line":24,"column":53,"index":959}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/growth'
    },
  'prestige-cycle': {
      name: 'prestige-cycle',
      description: 'Analyze optimal prestige cycle',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":883,"end":888,"loc":{"start":{"line":24,"column":54,"index":883},"end":{"line":24,"column":59,"index":888}},"value":false}}]}, validator: '(val) => true' },
        'scan': { type: 'z.string.default', required: true, hasDefault: true, default: "300..1800", description: 'Scan range (from..to)', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"300..1800"}]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Scan step sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1094,"end":1096,"loc":{"start":{"line":28,"column":43,"index":1094},"end":{"line":28,"column":45,"index":1096}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'horizon': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 3600, description: 'Horizon sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1180,"end":1184,"loc":{"start":{"line":29,"column":46,"index":1180},"end":{"line":29,"column":50,"index":1184}},"extra":{"rawValue":3600,"raw":"3600"},"value":3600}}]}, validator: '(val) => true' },
        'cycles': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 10, description: 'Cycle count', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1265,"end":1267,"loc":{"start":{"line":30,"column":45,"index":1265},"end":{"line":30,"column":47,"index":1267}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'objective': { type: 'z.enum.default', required: true, hasDefault: true, default: "netWorthPerHour", description: 'Optimization objective', enumValues: ["netWorthPerHour","pointsPerHour"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"netWorthPerHour"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/prestigeCycle'
    },
  'report': {
      name: 'report',
      description: 'Generate timeline report',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":856,"end":861,"loc":{"start":{"line":29,"column":54,"index":856},"end":{"line":29,"column":59,"index":861}},"value":false}}]}, validator: '(val) => true' },
        'checkpoints': { type: 'z.string.default', required: true, hasDefault: true, default: "60,300,900,3600", description: 'Comma-separated checkpoint seconds', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"60,300,900,3600"}]}, validator: '(val) => true' },
        'include-growth': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include growth report', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1117,"end":1122,"loc":{"start":{"line":35,"column":56,"index":1117},"end":{"line":35,"column":61,"index":1122}},"value":false}}]}, validator: '(val) => true' },
        'include-ux': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include UX flags', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1220,"end":1225,"loc":{"start":{"line":36,"column":52,"index":1220},"end":{"line":36,"column":57,"index":1225}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["md","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' }
      },
      path: './src/commands/report'
    },
  'simulate': {
      name: 'simulate',
      description: 'Run simulation with scenario',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":697,"end":702,"loc":{"start":{"line":20,"column":54,"index":697},"end":{"line":20,"column":59,"index":702}},"value":false}}]}, validator: '(val) => true' },
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'greedy|planner|scripted', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1076,"end":1081,"loc":{"start":{"line":26,"column":44,"index":1076},"end":{"line":26,"column":49,"index":1081}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/simulate'
    },
  'tune': {
      name: 'tune',
      description: 'Tune strategy parameters with objective scoring',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2291,"end":2296,"loc":{"start":{"line":77,"column":54,"index":2291},"end":{"line":77,"column":59,"index":2296}},"value":false}}]}, validator: '(val) => true' },
        'tune': { type: 'z.string.min', required: true, hasDefault: false, description: 'TuneSpec file path (.json|.yaml)', min: 1, minLength: 1, fileType: 'file', schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2398,"end":2399,"loc":{"start":{"line":80,"column":32,"index":2398},"end":{"line":80,"column":33,"index":2399}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/tune'
    },
  'validate': {
      name: 'validate',
      description: 'Validate scenario file',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin module paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":523,"end":528,"loc":{"start":{"line":14,"column":54,"index":523},"end":{"line":14,"column":59,"index":528}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/validate'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
