// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Compare from '../src/commands/compare.js'
import Eta from '../src/commands/eta.js'
import Growth from '../src/commands/growth.js'
import PrestigeCycle from '../src/commands/prestigeCycle.js'
import Report from '../src/commands/report.js'
import Simulate from '../src/commands/simulate.js'
import Tune from '../src/commands/tune.js'
import Validate from '../src/commands/validate.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['compare', 'eta', 'growth', 'prestige-cycle', 'report', 'simulate', 'tune', 'validate'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'compare': Compare,
  'eta': Eta,
  'growth': Growth,
  'prestige-cycle': PrestigeCycle,
  'report': Report,
  'simulate': Simulate,
  'tune': Tune,
  'validate': Validate
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'compare': {
      name: 'compare',
      description: 'Compare two scenarios via measured simulation metrics',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1204,"end":1209,"loc":{"start":{"line":37,"column":54,"index":1204},"end":{"line":37,"column":59,"index":1209}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1875,"end":1880,"loc":{"start":{"line":49,"column":44,"index":1875},"end":{"line":49,"column":49,"index":1880}},"value":false}}]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Required for etaToTargetWorth metric, optional otherwise', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max duration for etaToTargetWorth metric simulation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2125,"end":2130,"loc":{"start":{"line":53,"column":53,"index":2125},"end":{"line":53,"column":58,"index":2130}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'metric': { type: 'z.enum.default', required: true, hasDefault: true, default: "endNetWorth", description: 'Comparison metric', enumValues: ["endMoney","endNetWorth","etaToTargetWorth","droppedRate"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"endNetWorth"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/compare'
    },
  'eta': {
      name: 'eta',
      description: 'Estimate time to target money or net worth',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":671,"end":676,"loc":{"start":{"line":19,"column":54,"index":671},"end":{"line":19,"column":59,"index":676}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'target-money': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target money NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target net worth NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'mode': { type: 'z.enum.default', required: true, hasDefault: true, default: "simulate", description: 'ETA mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"simulate"}]}, validator: '(val) => true' },
        'diff': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Compare with another mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max simulate duration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1475,"end":1480,"loc":{"start":{"line":34,"column":53,"index":1475},"end":{"line":34,"column":58,"index":1480}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'include-run': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include detailed run payload in simulate mode output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1579,"end":1584,"loc":{"start":{"line":35,"column":53,"index":1579},"end":{"line":35,"column":58,"index":1584}},"value":false}}]}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Fast simulation mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1716,"end":1721,"loc":{"start":{"line":38,"column":44,"index":1716},"end":{"line":38,"column":49,"index":1721}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/eta'
    },
  'growth': {
      name: 'growth',
      description: 'Analyze growth regime from simulation trace',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":677,"end":682,"loc":{"start":{"line":19,"column":54,"index":677},"end":{"line":19,"column":59,"index":682}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'window': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Window sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1066,"end":1068,"loc":{"start":{"line":28,"column":45,"index":1066},"end":{"line":28,"column":47,"index":1068}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'series': { type: 'z.enum.default', required: true, hasDefault: true, default: "money", description: 'Series type', enumValues: ["money","netWorth"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"money"}]}, validator: '(val) => true' },
        'trace-every': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 1, description: 'Trace every N steps', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1255,"end":1256,"loc":{"start":{"line":30,"column":52,"index":1255},"end":{"line":30,"column":53,"index":1256}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/growth'
    },
  'prestige-cycle': {
      name: 'prestige-cycle',
      description: 'Analyze optimal prestige cycle',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":911,"end":916,"loc":{"start":{"line":24,"column":54,"index":911},"end":{"line":24,"column":59,"index":916}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'scan': { type: 'z.string.default', required: true, hasDefault: true, default: "300..1800", description: 'Scan range (from..to)', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"300..1800"}]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Scan step sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1391,"end":1393,"loc":{"start":{"line":34,"column":43,"index":1391},"end":{"line":34,"column":45,"index":1393}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'horizon': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 3600, description: 'Horizon sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1477,"end":1481,"loc":{"start":{"line":35,"column":46,"index":1477},"end":{"line":35,"column":50,"index":1481}},"extra":{"rawValue":3600,"raw":"3600"},"value":3600}}]}, validator: '(val) => true' },
        'cycles': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 10, description: 'Cycle count', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1562,"end":1564,"loc":{"start":{"line":36,"column":45,"index":1562},"end":{"line":36,"column":47,"index":1564}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'objective': { type: 'z.enum.default', required: true, hasDefault: true, default: "netWorthPerHour", description: 'Optimization objective', enumValues: ["netWorthPerHour","pointsPerHour"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"netWorthPerHour"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/prestigeCycle'
    },
  'report': {
      name: 'report',
      description: 'Generate timeline report',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":884,"end":889,"loc":{"start":{"line":29,"column":54,"index":884},"end":{"line":29,"column":59,"index":889}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'checkpoints': { type: 'z.string.default', required: true, hasDefault: true, default: "60,300,900,3600", description: 'Comma-separated checkpoint seconds', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"60,300,900,3600"}]}, validator: '(val) => true' },
        'include-growth': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include growth report', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1414,"end":1419,"loc":{"start":{"line":41,"column":56,"index":1414},"end":{"line":41,"column":61,"index":1419}},"value":false}}]}, validator: '(val) => true' },
        'include-ux': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include UX flags', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1517,"end":1522,"loc":{"start":{"line":42,"column":52,"index":1517},"end":{"line":42,"column":57,"index":1522}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["md","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' }
      },
      path: './src/commands/report'
    },
  'simulate': {
      name: 'simulate',
      description: 'Run simulation with scenario',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":725,"end":730,"loc":{"start":{"line":20,"column":54,"index":725},"end":{"line":20,"column":59,"index":730}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'greedy|planner|scripted', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1373,"end":1378,"loc":{"start":{"line":32,"column":44,"index":1373},"end":{"line":32,"column":49,"index":1378}},"value":false}}]}, validator: '(val) => true' },
        'event-log-enabled': { type: 'z.coerce.boolean.optional', required: false, hasDefault: false, description: 'Override event log retention enabled flag', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'event-log-max': { type: 'z.coerce.number.int.nonnegative.optional', required: false, hasDefault: false, description: 'Retain only latest N events in memory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/simulate'
    },
  'tune': {
      name: 'tune',
      description: 'Tune strategy parameters with objective scoring',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3351,"end":3356,"loc":{"start":{"line":114,"column":54,"index":3351},"end":{"line":114,"column":59,"index":3356}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'tune': { type: 'z.string.min', required: true, hasDefault: false, description: 'TuneSpec file path (.json|.yaml)', min: 1, minLength: 1, fileType: 'file', schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":3727,"end":3728,"loc":{"start":{"line":123,"column":32,"index":3727},"end":{"line":123,"column":33,"index":3728}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write tune artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'baseline-artifact': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Compare current best score against baseline artifact', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'regression-tolerance': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 0, description: 'Allowed score decrease before regression is flagged', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":4090,"end":4091,"loc":{"start":{"line":128,"column":61,"index":4090},"end":{"line":128,"column":62,"index":4091}},"extra":{"rawValue":0,"raw":"0"},"value":0}}]}, validator: '(val) => true' },
        'fail-on-regression': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Exit with error when regression is detected', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4238,"end":4243,"loc":{"start":{"line":131,"column":60,"index":4238},"end":{"line":131,"column":65,"index":4243}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/tune'
    },
  'validate': {
      name: 'validate',
      description: 'Validate scenario file',
      options: {
        'plugin': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated plugin module paths', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'allow-plugin': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow loading local plugin modules', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":551,"end":556,"loc":{"start":{"line":14,"column":54,"index":551},"end":{"line":14,"column":59,"index":556}},"value":false}}]}, validator: '(val) => true' },
        'plugin-root': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated allowed plugin root directories', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' },
        'plugin-sha256': { type: 'z.string.default', required: true, hasDefault: true, default: "", description: 'Comma-separated \'<path>=<sha256>\' plugin integrity map', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":""}]}, validator: '(val) => true' }
      },
      path: './src/commands/validate'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
