// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Calibrate from '../src/commands/calibrate.js'
import Compare from '../src/commands/compare.js'
import Doctor from '../src/commands/doctor.js'
import Eta from '../src/commands/eta.js'
import Evaluate from '../src/commands/evaluate.js'
import Experience from '../src/commands/experience.js'
import Growth from '../src/commands/growth.js'
import Init from '../src/commands/groups/init.js'
import Kpi from '../src/commands/groups/kpi.js'
import Ltv from '../src/commands/ltv.js'
import Models from '../src/commands/groups/models.js'
import Objectives from '../src/commands/groups/objectives.js'
import PrestigeCycle from '../src/commands/prestigeCycle.js'
import Replay from '../src/commands/groups/replay.js'
import Report from '../src/commands/report.js'
import Review from '../src/commands/groups/review.js'
import Simulate from '../src/commands/simulate.js'
import Strategies from '../src/commands/groups/strategies.js'
import Tune from '../src/commands/tune.js'
import Validate from '../src/commands/validate.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['calibrate', 'compare', 'doctor', 'eta', 'evaluate', 'experience', 'growth', 'init', 'kpi', 'ltv', 'models', 'objectives', 'prestige-cycle', 'replay', 'report', 'review', 'simulate', 'strategies', 'tune', 'validate'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'calibrate': Calibrate,
  'compare': Compare,
  'doctor': Doctor,
  'eta': Eta,
  'evaluate': Evaluate,
  'experience': Experience,
  'growth': Growth,
  'init': Init,
  'kpi': Kpi,
  'ltv': Ltv,
  'models': Models,
  'objectives': Objectives,
  'prestige-cycle': PrestigeCycle,
  'replay': Replay,
  'report': Report,
  'review': Review,
  'simulate': Simulate,
  'strategies': Strategies,
  'tune': Tune,
  'validate': Validate
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'calibrate': {
      name: 'calibrate',
      description: 'Calibrate monetization parameters from telemetry rows (CSV/JSON)',
      options: {
        'input-format': { type: 'z.enum.default', required: true, hasDefault: true, default: "auto", description: 'Telemetry file format', enumValues: ["auto","csv","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"auto"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/calibrate'
    },
  'compare': {
      name: 'compare',
      description: 'Compare two scenarios via measured simulation metrics',
      options: {
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":17720,"end":17725,"loc":{"start":{"line":526,"column":44,"index":17720},"end":{"line":526,"column":49,"index":17725}},"value":false}}]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Required for etaToTargetWorth metric, optional otherwise', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'milestone-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Required for timeToMilestone metric; compared against milestone report keys', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'session-pattern': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Session pattern for design metrics', enumValues: ["always-on","short-bursts","twice-daily","offline-heavy","weekend-marathon"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Session-pattern day count for design metrics', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draw count for design metrics', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max duration for etaToTargetWorth metric simulation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":18616,"end":18621,"loc":{"start":{"line":543,"column":53,"index":18616},"end":{"line":543,"column":58,"index":18621}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed passed to ctx.seed', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'run-id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional run identifier used in output metadata', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write replay artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'metric': { type: 'compareMetricSchema.optional', required: false, hasDefault: false, description: 'Comparison metric', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'bundle': { type: 'compareBundleSchema', required: true, hasDefault: false, description: 'Run a predefined metric bundle (economy|design|full)', schema: {"type":"zod","name":"compareBundleSchema"}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/compare'
    },
  'doctor': {
      name: 'doctor',
      description: 'Check runtime, generated metadata, and completions wiring',
      options: {
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["json","md"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' },
        'shell': { type: 'z.enum.default', required: true, hasDefault: true, default: "zsh", description: 'Completion shell to validate', enumValues: ["zsh","bash","fish","powershell"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"zsh"}]}, validator: '(val) => true' }
      },
      path: './src/commands/doctor'
    },
  'eta': {
      name: 'eta',
      description: 'Estimate time to target money or net worth',
      options: {
        'target-money': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target money NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Target net worth NumStr', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'mode': { type: 'z.enum.default', required: true, hasDefault: true, default: "simulate", description: 'ETA mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"simulate"}]}, validator: '(val) => true' },
        'diff': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Compare with another mode', enumValues: ["simulate","analytic"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max simulate duration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1102,"end":1107,"loc":{"start":{"line":27,"column":53,"index":1102},"end":{"line":27,"column":58,"index":1107}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
        'include-run': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include detailed run payload in simulate mode output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1206,"end":1211,"loc":{"start":{"line":28,"column":53,"index":1206},"end":{"line":28,"column":58,"index":1211}},"value":false}}]}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Fast simulation mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1343,"end":1348,"loc":{"start":{"line":31,"column":44,"index":1343},"end":{"line":31,"column":49,"index":1348}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/eta'
    },
  'evaluate': {
      name: 'evaluate',
      description: 'Run validate + simulate + experience + ltv as one workflow',
      options: {
        'session-pattern': { type: 'sessionPatternSchema', required: true, hasDefault: false, description: 'Session pattern override for experience', schema: {"type":"zod","name":"sessionPatternSchema"}, validator: '(val) => true' },
        'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Session-pattern day count for experience', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draw count for experience', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed override', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast mode for simulate/ltv', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4378,"end":4383,"loc":{"start":{"line":111,"column":44,"index":4378},"end":{"line":111,"column":49,"index":4383}},"value":false}}]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.positive.optional', required: false, hasDefault: false, description: 'Override stepSec for simulate/ltv', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'horizons': { type: 'z.string.default', required: true, hasDefault: true, default: "30m,2h,24h,7d,30d,90d", description: 'LTV horizons override', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"30m,2h,24h,7d,30d,90d"}]}, validator: '(val) => true' },
        'out-dir': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional directory to save simulate/experience/ltv/summary outputs', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Summary output format', enumValues: ["json","md"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/evaluate'
    },
  'experience': {
      name: 'experience',
      description: 'Evaluate design-facing progression, milestones, session pattern, and perceived feedback',
      options: {
        'session-pattern': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Session pattern id', enumValues: ["always-on","short-bursts","twice-daily","offline-heavy","weekend-marathon"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Days to simulate for the session pattern', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draw count (1 = deterministic)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' },
        'run-id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional run identifier used in output metadata', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write replay artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/experience'
    },
  'growth': {
      name: 'growth',
      description: 'Analyze growth regime from simulation trace',
      options: {
        'window': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Window sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":693,"end":695,"loc":{"start":{"line":21,"column":45,"index":693},"end":{"line":21,"column":47,"index":695}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'series': { type: 'z.enum.default', required: true, hasDefault: true, default: "money", description: 'Series type', enumValues: ["money","netWorth"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"money"}]}, validator: '(val) => true' },
        'trace-every': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 1, description: 'Trace every N steps', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":882,"end":883,"loc":{"start":{"line":23,"column":52,"index":882},"end":{"line":23,"column":53,"index":883}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/growth'
    },
  'init': {
      name: 'init',
      description: 'Scaffold templates',
      commands: [
        {
          name: 'scenario',
          description: 'Generate a starter scenario template',
          options: {
            'out': { type: 'z.string.default', required: true, hasDefault: true, default: "./tmp/new-scenario.json", description: 'Output scenario path (personal track also writes compare/tune siblings)', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"./tmp/new-scenario.json"}]}, validator: '(val) => true' },
            'track': { type: 'z.enum.default', required: true, hasDefault: true, default: "intro", description: 'Template track (intro|design|personal)', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"intro"}]}, validator: '(val) => true' },
            'preset': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Template preset (session|builder|longrun)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional personal track name. Changes generated file stem + meta id/title.', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'wizard': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Launch an interactive wizard for template customization', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1750,"end":1755,"loc":{"start":{"line":47,"column":46,"index":1750},"end":{"line":47,"column":51,"index":1755}},"value":false}}]}, validator: '(val) => true' },
            'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Overwrite output file when already exists', fileType: 'file', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1891,"end":1896,"loc":{"start":{"line":50,"column":45,"index":1891},"end":{"line":50,"column":50,"index":1896}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/initScenario'
        }
      ],
      path: './src/commands/groups/init'
    },
  'kpi': {
      name: 'kpi',
      description: 'KPI guardrail commands',
      commands: [
        {
          name: 'regress',
          description: 'Run long-horizon KPI regression gate',
          options: {
            'baseline': { type: 'z.string.default', required: true, hasDefault: true, default: "examples/bench/kpi-baseline.json", description: 'Baseline KPI report path', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"examples/bench/kpi-baseline.json"}]}, validator: '(val) => true' },
            'current': { type: 'z.string.default', required: true, hasDefault: true, default: "tmp/kpi-report.json", description: 'Current KPI report path', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"tmp/kpi-report.json"}]}, validator: '(val) => true' },
            'min-worth-ratio': { type: 'z.coerce.number.positive.default', required: true, hasDefault: true, default: 0.97, description: 'Minimum allowed current/baseline endNetWorth ratio', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1863,"end":1867,"loc":{"start":{"line":57,"column":67,"index":1863},"end":{"line":57,"column":71,"index":1867}},"extra":{"rawValue":0.97,"raw":"0.97"},"value":0.97}}]}, validator: '(val) => true' },
            'max-stall-delta': { type: 'z.coerce.number.nonnegative.default', required: true, hasDefault: true, default: 0.03, description: 'Maximum allowed stallRatio increase', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2023,"end":2027,"loc":{"start":{"line":60,"column":70,"index":2023},"end":{"line":60,"column":74,"index":2027}},"extra":{"rawValue":0.03,"raw":"0.03"},"value":0.03}}]}, validator: '(val) => true' },
            'max-dropped-delta': { type: 'z.coerce.number.nonnegative.default', required: true, hasDefault: true, default: 0.03, description: 'Maximum allowed droppedRate increase', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2170,"end":2174,"loc":{"start":{"line":63,"column":72,"index":2170},"end":{"line":63,"column":76,"index":2174}},"extra":{"rawValue":0.03,"raw":"0.03"},"value":0.03}}]}, validator: '(val) => true' },
            'min-visible-progress-ratio': { type: 'z.coerce.number.positive.default', required: true, hasDefault: true, default: 0.9, description: 'Minimum allowed current/baseline visibleChangesPerMinute ratio', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2324,"end":2327,"loc":{"start":{"line":66,"column":78,"index":2324},"end":{"line":66,"column":81,"index":2327}},"extra":{"rawValue":0.9,"raw":"0.9"},"value":0.9}}]}, validator: '(val) => true' },
            'max-no-reward-gap-delta': { type: 'z.coerce.number.nonnegative.default', required: true, hasDefault: true, default: 60, description: 'Maximum allowed maxNoRewardGapSec increase', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2503,"end":2505,"loc":{"start":{"line":69,"column":78,"index":2503},"end":{"line":69,"column":80,"index":2505}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
            'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
          },
          path: './src/commands/kpiRegress'
        }
      ],
      path: './src/commands/groups/kpi'
    },
  'ltv': {
      name: 'ltv',
      description: 'Compute long-horizon LTV snapshots (30m..90d) and uncertainty bands',
      options: {
        'horizons': { type: 'z.string.default', required: true, hasDefault: true, default: "30m,2h,24h,7d,30d,90d", description: 'Comma-separated duration tokens (s|m|h|d)', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"30m,2h,24h,7d,30d,90d"}]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.positive.optional', required: false, hasDefault: false, description: 'Override stepSec for long-horizon runs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode for long horizons', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5519,"end":5524,"loc":{"start":{"line":162,"column":44,"index":5519},"end":{"line":162,"column":49,"index":5524}},"value":false}}]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed passed to ctx.seed', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'value-per-worth': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Optional conversion factor from netWorth to business value', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draws override (uses scenario.monetization.uncertainty.draws by default)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'run-id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional run identifier used in output metadata', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write replay artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/ltv'
    },
  'models': {
      name: 'models',
      description: 'Model registry commands',
      commands: [
        {
          name: 'list',
          description: 'List available models',
          options: {
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' },
            'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output file path', fileType: 'file', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/modelsList'
        }
      ],
      path: './src/commands/groups/models'
    },
  'objectives': {
      name: 'objectives',
      description: 'Objective registry commands',
      commands: [
        {
          name: 'list',
          description: 'List optimization objectives',
          options: {
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' },
            'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output file path', fileType: 'file', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/objectives'
        }
      ],
      path: './src/commands/groups/objectives'
    },
  'prestige-cycle': {
      name: 'prestige-cycle',
      description: 'Analyze optimal prestige cycle',
      options: {
        'scan': { type: 'z.string.default', required: true, hasDefault: true, default: "300..1800", description: 'Scan range (from..to)', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"300..1800"}]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 60, description: 'Scan step sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1040,"end":1042,"loc":{"start":{"line":27,"column":43,"index":1040},"end":{"line":27,"column":45,"index":1042}},"extra":{"rawValue":60,"raw":"60"},"value":60}}]}, validator: '(val) => true' },
        'horizon': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 3600, description: 'Horizon sec', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1126,"end":1130,"loc":{"start":{"line":28,"column":46,"index":1126},"end":{"line":28,"column":50,"index":1130}},"extra":{"rawValue":3600,"raw":"3600"},"value":3600}}]}, validator: '(val) => true' },
        'cycles': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 10, description: 'Cycle count', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1211,"end":1213,"loc":{"start":{"line":29,"column":45,"index":1211},"end":{"line":29,"column":47,"index":1213}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'objective': { type: 'z.enum.default', required: true, hasDefault: true, default: "netWorthPerHour", description: 'Optimization objective', enumValues: ["netWorthPerHour","pointsPerHour"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"netWorthPerHour"}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/prestigeCycle'
    },
  'replay': {
      name: 'replay',
      description: 'Replay artifact commands',
      commands: [
        {
          name: 'verify',
          description: 'Verify replay artifact reproducibility',
          options: {
            'strict': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: true, description: 'Exit with error if replay verification fails', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2435,"end":2439,"loc":{"start":{"line":73,"column":46,"index":2435},"end":{"line":73,"column":50,"index":2439}},"value":true}}]}, validator: '(val) => true' },
            'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
          },
          path: './src/commands/replayVerify'
        }
      ],
      path: './src/commands/groups/replay'
    },
  'report': {
      name: 'report',
      description: 'Generate timeline report',
      options: {
        'checkpoints': { type: 'z.string.default', required: true, hasDefault: true, default: "60,300,900,3600", description: 'Comma-separated checkpoint seconds', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"60,300,900,3600"}]}, validator: '(val) => true' },
        'include-growth': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include growth report', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1156,"end":1161,"loc":{"start":{"line":35,"column":56,"index":1156},"end":{"line":35,"column":61,"index":1161}},"value":false}}]}, validator: '(val) => true' },
        'include-ux': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include UX flags', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1259,"end":1264,"loc":{"start":{"line":36,"column":52,"index":1259},"end":{"line":36,"column":57,"index":1264}},"value":false}}]}, validator: '(val) => true' },
        'include-milestones': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include milestone report', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1365,"end":1370,"loc":{"start":{"line":37,"column":60,"index":1365},"end":{"line":37,"column":65,"index":1370}},"value":false}}]}, validator: '(val) => true' },
        'include-perceived': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include perceived progression report', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1478,"end":1483,"loc":{"start":{"line":38,"column":59,"index":1478},"end":{"line":38,"column":64,"index":1483}},"value":false}}]}, validator: '(val) => true' },
        'session-pattern': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Session pattern for milestone/perceived report sections', enumValues: ["always-on","short-bursts","twice-daily","offline-heavy","weekend-marathon"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Session-pattern day count for milestone/perceived report sections', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["md","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' }
      },
      path: './src/commands/report'
    },
  'review': {
      name: 'review',
      description: 'Interactive human-review dashboards',
      commands: [
        {
          name: 'evaluate',
          description: 'Interactive evaluate dashboard for human design review',
          options: {
            'session-pattern': { type: 'sessionPatternSchema', required: true, hasDefault: false, description: 'Session pattern override for review data', schema: {"type":"zod","name":"sessionPatternSchema"}, validator: '(val) => true' },
            'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Session-pattern day count override', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draw count override', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed override', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
            'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast mode for evaluate child runs', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2636,"end":2641,"loc":{"start":{"line":76,"column":44,"index":2636},"end":{"line":76,"column":49,"index":2641}},"value":false}}]}, validator: '(val) => true' },
            'step': { type: 'z.coerce.number.positive.optional', required: false, hasDefault: false, description: 'Override stepSec for evaluate child runs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'horizons': { type: 'z.string.default', required: true, hasDefault: true, default: "30m,2h,24h,7d,30d,90d", description: 'LTV horizons override', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"30m,2h,24h,7d,30d,90d"}]}, validator: '(val) => true' }
          },
          path: './src/commands/reviewEvaluate'
        },
        {
          name: 'compare',
          description: 'Interactive compare dashboard for human design review',
          options: {
            'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'Override strategy id (greedy|planner|scripted)', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
            'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2628,"end":2633,"loc":{"start":{"line":77,"column":44,"index":2628},"end":{"line":77,"column":49,"index":2633}},"value":false}}]}, validator: '(val) => true' },
            'target-worth': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Required for etaToTargetWorth metric, optional otherwise', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'milestone-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Milestone key override for design bundles or timeToMilestone metric', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'session-pattern': { type: 'sessionPatternSchema', required: true, hasDefault: false, description: 'Session pattern override for design metrics', schema: {"type":"zod","name":"sessionPatternSchema"}, validator: '(val) => true' },
            'days': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Session-pattern day count for design metrics', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'draws': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Monte Carlo draw count for design metrics', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'max-duration': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 86400, description: 'Max duration for etaToTargetWorth metric simulation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":3437,"end":3442,"loc":{"start":{"line":93,"column":53,"index":3437},"end":{"line":93,"column":58,"index":3442}},"extra":{"rawValue":86400,"raw":"86400"},"value":86400}}]}, validator: '(val) => true' },
            'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'metric': { type: 'compareMetricSchema.optional', required: false, hasDefault: false, description: 'Single comparison metric', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'bundle': { type: 'compareBundleSchema', required: true, hasDefault: false, description: 'Bundle of comparison metrics', schema: {"type":"zod","name":"compareBundleSchema"}, validator: '(val) => true' }
          },
          path: './src/commands/reviewCompare'
        }
      ],
      path: './src/commands/groups/review'
    },
  'simulate': {
      name: 'simulate',
      description: 'Run simulation with scenario',
      options: {
        'duration': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override durationSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'step': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Override stepSec', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'strategy': { type: 'strategySchema', required: true, hasDefault: false, description: 'greedy|planner|scripted', schema: {"type":"zod","name":"strategySchema"}, validator: '(val) => true' },
        'fast': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable fast(log-domain) mode', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3346,"end":3351,"loc":{"start":{"line":89,"column":44,"index":3346},"end":{"line":89,"column":49,"index":3351}},"value":false}}]}, validator: '(val) => true' },
        'event-log-enabled': { type: 'z.coerce.boolean.optional', required: false, hasDefault: false, description: 'Override event log retention enabled flag', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'event-log-max': { type: 'z.coerce.number.int.nonnegative.optional', required: false, hasDefault: false, description: 'Retain only latest N events in memory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'offline-seconds': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Apply offline catch-up before simulation starts', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'resume': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Resume simulation from saved state json', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'state-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write end simulation state json', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write replay artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Deterministic seed passed to ctx.seed', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'run-id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional run identifier (auto-generated if omitted)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/simulate'
    },
  'strategies': {
      name: 'strategies',
      description: 'Strategy registry commands',
      commands: [
        {
          name: 'list',
          description: 'List available strategies',
          options: {
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "md", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"md"}]}, validator: '(val) => true' },
            'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output file path', fileType: 'file', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/strategies'
        }
      ],
      path: './src/commands/groups/strategies'
    },
  'tune': {
      name: 'tune',
      description: 'Tune strategy parameters with objective scoring',
      options: {
        'tune': { type: 'z.string.min', required: true, hasDefault: false, description: 'TuneSpec file path (.json|.yaml)', min: 1, minLength: 1, fileType: 'file', schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":5712,"end":5713,"loc":{"start":{"line":177,"column":32,"index":5712},"end":{"line":177,"column":33,"index":5713}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'seed': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Optional deterministic seed exposed in metadata/replay verification', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'artifact-out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Write tune artifact JSON to path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'baseline-artifact': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Compare current best score against baseline artifact', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'run-id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Optional run identifier used in output metadata', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'regression-tolerance': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 0, description: 'Allowed score decrease before regression is flagged', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":6346,"end":6347,"loc":{"start":{"line":188,"column":61,"index":6346},"end":{"line":188,"column":62,"index":6347}},"extra":{"rawValue":0,"raw":"0"},"value":0}}]}, validator: '(val) => true' },
        'fail-on-regression': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Exit with error when regression is detected', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6494,"end":6499,"loc":{"start":{"line":191,"column":60,"index":6494},"end":{"line":191,"column":65,"index":6499}},"value":false}}]}, validator: '(val) => true' },
        'out': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output path', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["json","md","csv"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/tune'
    },
  'validate': {
      name: 'validate',
      description: 'Validate scenario file',
      path: './src/commands/validate'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
